#############################################################################
# Makefile for building: ../bin/nzgui
# Generated by qmake (2.01a) (Qt 4.7.3) on: Thu Aug 18 15:20:14 2011
# Project:  nzgui.pro
# Template: app
# Command: /usr/bin/qmake -o qmake.mk nzgui.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtWebKit -I/usr/include -Ihdr -I../nzlib/hdr -Igen
LINK          = g++
LFLAGS        = -m64 -Wl,--hash-style=gnu -Wl,--as-needed
LIBS          = $(SUBLIBS)  -L/usr/lib -L../lib -lnzlib -lmd5 -lQtWebKit -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ../obj/nzgui/

####### Files

SOURCES       = src/NZAddChatDialog.cc \
		src/NZAddContactDialog.cc \
		src/NZChatView.cc \
		src/NZChatWidget.cc \
		src/NZConnectionWidget.cc \
		src/NZContact.cc \
		src/NZContactListWidget.cc \
		src/NZContactModel.cc \
		src/NZControllerProxy.cc \
		src/NZConversation.cc \
		src/NZGuiController.cc \
		src/NZMainWindow.cc \
		src/NZMessage.cc \
		src/NZSideBarWidget.cc \
		src/NZStatusWidget.cc \
		src/NZWaitWidget.cc \
		src/main.cc gen/moc_NZAddChatDialog.cpp \
		gen/moc_NZAddContactDialog.cpp \
		gen/moc_NZChatView.cpp \
		gen/moc_NZChatWidget.cpp \
		gen/moc_NZConnectionWidget.cpp \
		gen/moc_NZContact.cpp \
		gen/moc_NZContactListWidget.cpp \
		gen/moc_NZContactModel.cpp \
		gen/moc_NZControllerProxy.cpp \
		gen/moc_NZConversation.cpp \
		gen/moc_NZGuiController.cpp \
		gen/moc_NZMainWindow.cpp \
		gen/moc_NZSideBarWidget.cpp \
		gen/moc_NZStatusWidget.cpp \
		gen/qrc_nzgui.cpp
OBJECTS       = ../obj/nzgui/NZAddChatDialog.o \
		../obj/nzgui/NZAddContactDialog.o \
		../obj/nzgui/NZChatView.o \
		../obj/nzgui/NZChatWidget.o \
		../obj/nzgui/NZConnectionWidget.o \
		../obj/nzgui/NZContact.o \
		../obj/nzgui/NZContactListWidget.o \
		../obj/nzgui/NZContactModel.o \
		../obj/nzgui/NZControllerProxy.o \
		../obj/nzgui/NZConversation.o \
		../obj/nzgui/NZGuiController.o \
		../obj/nzgui/NZMainWindow.o \
		../obj/nzgui/NZMessage.o \
		../obj/nzgui/NZSideBarWidget.o \
		../obj/nzgui/NZStatusWidget.o \
		../obj/nzgui/NZWaitWidget.o \
		../obj/nzgui/main.o \
		../obj/nzgui/moc_NZAddChatDialog.o \
		../obj/nzgui/moc_NZAddContactDialog.o \
		../obj/nzgui/moc_NZChatView.o \
		../obj/nzgui/moc_NZChatWidget.o \
		../obj/nzgui/moc_NZConnectionWidget.o \
		../obj/nzgui/moc_NZContact.o \
		../obj/nzgui/moc_NZContactListWidget.o \
		../obj/nzgui/moc_NZContactModel.o \
		../obj/nzgui/moc_NZControllerProxy.o \
		../obj/nzgui/moc_NZConversation.o \
		../obj/nzgui/moc_NZGuiController.o \
		../obj/nzgui/moc_NZMainWindow.o \
		../obj/nzgui/moc_NZSideBarWidget.o \
		../obj/nzgui/moc_NZStatusWidget.o \
		../obj/nzgui/qrc_nzgui.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		../mk/qt.pri \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		nzgui.pro
QMAKE_TARGET  = nzgui
DESTDIR       = ../bin/
TARGET        = ../bin/nzgui

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: qmake.mk $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ../bin/ || $(MKDIR) ../bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

qmake.mk: nzgui.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		../mk/qt.pri \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o qmake.mk nzgui.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
../mk/qt.pri:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o qmake.mk nzgui.pro

dist: 
	@$(CHK_DIR_EXISTS) ../obj/nzgui/nzgui1.0.0 || $(MKDIR) ../obj/nzgui/nzgui1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) ../obj/nzgui/nzgui1.0.0/ && $(COPY_FILE) --parents hdr/NZAddChatDialog.hh hdr/NZAddContactDialog.hh hdr/NZChatView.hh hdr/NZChatWidget.hh hdr/NZConnectionWidget.hh hdr/NZContact.hh hdr/NZContactListWidget.hh hdr/NZContactModel.hh hdr/NZControllerProxy.hh hdr/NZConversation.hh hdr/NZGuiController.hh hdr/NZMainWindow.hh hdr/NZMessage.hh hdr/NZSideBarWidget.hh hdr/NZStatusWidget.hh hdr/NZWaitWidget.hh ../obj/nzgui/nzgui1.0.0/ && $(COPY_FILE) --parents nzgui.qrc ../obj/nzgui/nzgui1.0.0/ && $(COPY_FILE) --parents src/NZAddChatDialog.cc src/NZAddContactDialog.cc src/NZChatView.cc src/NZChatWidget.cc src/NZConnectionWidget.cc src/NZContact.cc src/NZContactListWidget.cc src/NZContactModel.cc src/NZControllerProxy.cc src/NZConversation.cc src/NZGuiController.cc src/NZMainWindow.cc src/NZMessage.cc src/NZSideBarWidget.cc src/NZStatusWidget.cc src/NZWaitWidget.cc src/main.cc ../obj/nzgui/nzgui1.0.0/ && (cd `dirname ../obj/nzgui/nzgui1.0.0` && $(TAR) nzgui1.0.0.tar nzgui1.0.0 && $(COMPRESS) nzgui1.0.0.tar) && $(MOVE) `dirname ../obj/nzgui/nzgui1.0.0`/nzgui1.0.0.tar.gz . && $(DEL_FILE) -r ../obj/nzgui/nzgui1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) qmake.mk


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: gen/moc_NZAddChatDialog.cpp gen/moc_NZAddContactDialog.cpp gen/moc_NZChatView.cpp gen/moc_NZChatWidget.cpp gen/moc_NZConnectionWidget.cpp gen/moc_NZContact.cpp gen/moc_NZContactListWidget.cpp gen/moc_NZContactModel.cpp gen/moc_NZControllerProxy.cpp gen/moc_NZConversation.cpp gen/moc_NZGuiController.cpp gen/moc_NZMainWindow.cpp gen/moc_NZSideBarWidget.cpp gen/moc_NZStatusWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) gen/moc_NZAddChatDialog.cpp gen/moc_NZAddContactDialog.cpp gen/moc_NZChatView.cpp gen/moc_NZChatWidget.cpp gen/moc_NZConnectionWidget.cpp gen/moc_NZContact.cpp gen/moc_NZContactListWidget.cpp gen/moc_NZContactModel.cpp gen/moc_NZControllerProxy.cpp gen/moc_NZConversation.cpp gen/moc_NZGuiController.cpp gen/moc_NZMainWindow.cpp gen/moc_NZSideBarWidget.cpp gen/moc_NZStatusWidget.cpp
gen/moc_NZAddChatDialog.cpp: hdr/NZAddChatDialog.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZAddChatDialog.hh -o gen/moc_NZAddChatDialog.cpp

gen/moc_NZAddContactDialog.cpp: hdr/NZAddContactDialog.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZAddContactDialog.hh -o gen/moc_NZAddContactDialog.cpp

gen/moc_NZChatView.cpp: hdr/NZChatView.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZChatView.hh -o gen/moc_NZChatView.cpp

gen/moc_NZChatWidget.cpp: hdr/NZChatWidget.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZChatWidget.hh -o gen/moc_NZChatWidget.cpp

gen/moc_NZConnectionWidget.cpp: hdr/NZConnectionWidget.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZConnectionWidget.hh -o gen/moc_NZConnectionWidget.cpp

gen/moc_NZContact.cpp: hdr/NZContact.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZContact.hh -o gen/moc_NZContact.cpp

gen/moc_NZContactListWidget.cpp: hdr/NZContactListWidget.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZContactListWidget.hh -o gen/moc_NZContactListWidget.cpp

gen/moc_NZContactModel.cpp: hdr/NZContact.hh \
		hdr/NZContactModel.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZContactModel.hh -o gen/moc_NZContactModel.cpp

gen/moc_NZControllerProxy.cpp: hdr/NZControllerProxy.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZControllerProxy.hh -o gen/moc_NZControllerProxy.cpp

gen/moc_NZConversation.cpp: hdr/NZConversation.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZConversation.hh -o gen/moc_NZConversation.cpp

gen/moc_NZGuiController.cpp: hdr/NZContact.hh \
		hdr/NZGuiController.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZGuiController.hh -o gen/moc_NZGuiController.cpp

gen/moc_NZMainWindow.cpp: hdr/NZContact.hh \
		hdr/NZStatusWidget.hh \
		hdr/NZSideBarWidget.hh \
		hdr/NZContactListWidget.hh \
		hdr/NZChatWidget.hh \
		hdr/NZConnectionWidget.hh \
		hdr/NZWaitWidget.hh \
		hdr/NZMainWindow.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZMainWindow.hh -o gen/moc_NZMainWindow.cpp

gen/moc_NZSideBarWidget.cpp: hdr/NZSideBarWidget.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZSideBarWidget.hh -o gen/moc_NZSideBarWidget.cpp

gen/moc_NZStatusWidget.cpp: hdr/NZContact.hh \
		hdr/NZStatusWidget.hh
	/usr/bin/moc $(DEFINES) $(INCPATH) hdr/NZStatusWidget.hh -o gen/moc_NZStatusWidget.cpp

compiler_rcc_make_all: gen/qrc_nzgui.cpp
compiler_rcc_clean:
	-$(DEL_FILE) gen/qrc_nzgui.cpp
gen/qrc_nzgui.cpp: nzgui.qrc \
		res/html/conversation.css \
		res/html/conversation.js \
		res/html/conversation.html \
		res/icon/128.png \
		res/icon/64.png \
		res/icon/32.png \
		res/icon/48.png \
		res/icon/256.png \
		res/icon/16.png \
		res/16/user.png \
		res/16/lock.png \
		res/16/server.png \
		res/16/plug.png \
		res/16/address-book.png \
		res/16/balloons.png \
		res/16/minus-circle.png \
		res/16/tick.png \
		res/16/cross.png \
		res/24/user-minus-circle.png \
		res/24/user.png \
		res/24/user-lock.png \
		res/24/user-server.png \
		res/24/balloon-add.png \
		res/24/user-add.png \
		res/24/user-cross.png
	/usr/bin/rcc -name nzgui nzgui.qrc -o gen/qrc_nzgui.cpp

compiler_image_collection_make_all: gen/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) gen/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

../obj/nzgui/NZAddChatDialog.o: src/NZAddChatDialog.cc hdr/NZAddChatDialog.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZAddChatDialog.o src/NZAddChatDialog.cc

../obj/nzgui/NZAddContactDialog.o: src/NZAddContactDialog.cc hdr/NZAddContactDialog.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZAddContactDialog.o src/NZAddContactDialog.cc

../obj/nzgui/NZChatView.o: src/NZChatView.cc hdr/NZChatView.hh \
		hdr/NZConversation.hh \
		hdr/NZMessage.hh \
		hdr/NZGuiController.hh \
		hdr/NZContact.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZChatView.o src/NZChatView.cc

../obj/nzgui/NZChatWidget.o: src/NZChatWidget.cc hdr/NZConversation.hh \
		hdr/NZChatView.hh \
		hdr/NZChatWidget.hh \
		hdr/NZContact.hh \
		hdr/NZMessage.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZChatWidget.o src/NZChatWidget.cc

../obj/nzgui/NZConnectionWidget.o: src/NZConnectionWidget.cc hdr/NZConnectionWidget.hh \
		hdr/NZGuiController.hh \
		hdr/NZContact.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZConnectionWidget.o src/NZConnectionWidget.cc

../obj/nzgui/NZContact.o: src/NZContact.cc hdr/NZContact.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZContact.o src/NZContact.cc

../obj/nzgui/NZContactListWidget.o: src/NZContactListWidget.cc hdr/NZContactListWidget.hh \
		hdr/NZContact.hh \
		hdr/NZContactModel.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZContactListWidget.o src/NZContactListWidget.cc

../obj/nzgui/NZContactModel.o: src/NZContactModel.cc hdr/NZContactModel.hh \
		hdr/NZContact.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZContactModel.o src/NZContactModel.cc

../obj/nzgui/NZControllerProxy.o: src/NZControllerProxy.cc hdr/NZControllerProxy.hh \
		hdr/NZControllerDelegate.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZControllerProxy.o src/NZControllerProxy.cc

../obj/nzgui/NZConversation.o: src/NZConversation.cc hdr/NZConversation.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZConversation.o src/NZConversation.cc

../obj/nzgui/NZGuiController.o: src/NZGuiController.cc hdr/NZGuiController.hh \
		hdr/NZContact.hh \
		hdr/NZMainWindow.hh \
		hdr/NZStatusWidget.hh \
		hdr/NZSideBarWidget.hh \
		hdr/NZContactListWidget.hh \
		hdr/NZChatWidget.hh \
		hdr/NZConnectionWidget.hh \
		hdr/NZWaitWidget.hh \
		hdr/NZControllerProxy.hh \
		hdr/NZAddContactDialog.hh \
		hdr/NZAddChatDialog.hh \
		hdr/NZConversation.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZGuiController.o src/NZGuiController.cc

../obj/nzgui/NZMainWindow.o: src/NZMainWindow.cc hdr/NZMainWindow.hh \
		hdr/NZContact.hh \
		hdr/NZStatusWidget.hh \
		hdr/NZSideBarWidget.hh \
		hdr/NZContactListWidget.hh \
		hdr/NZChatWidget.hh \
		hdr/NZConnectionWidget.hh \
		hdr/NZWaitWidget.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZMainWindow.o src/NZMainWindow.cc

../obj/nzgui/NZMessage.o: src/NZMessage.cc hdr/NZMessage.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZMessage.o src/NZMessage.cc

../obj/nzgui/NZSideBarWidget.o: src/NZSideBarWidget.cc hdr/NZSideBarWidget.hh \
		hdr/NZConversation.hh \
		hdr/NZContact.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZSideBarWidget.o src/NZSideBarWidget.cc

../obj/nzgui/NZStatusWidget.o: src/NZStatusWidget.cc hdr/NZStatusWidget.hh \
		hdr/NZContact.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZStatusWidget.o src/NZStatusWidget.cc

../obj/nzgui/NZWaitWidget.o: src/NZWaitWidget.cc hdr/NZWaitWidget.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/NZWaitWidget.o src/NZWaitWidget.cc

../obj/nzgui/main.o: src/main.cc hdr/NZGuiController.hh \
		hdr/NZContact.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/main.o src/main.cc

../obj/nzgui/moc_NZAddChatDialog.o: gen/moc_NZAddChatDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZAddChatDialog.o gen/moc_NZAddChatDialog.cpp

../obj/nzgui/moc_NZAddContactDialog.o: gen/moc_NZAddContactDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZAddContactDialog.o gen/moc_NZAddContactDialog.cpp

../obj/nzgui/moc_NZChatView.o: gen/moc_NZChatView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZChatView.o gen/moc_NZChatView.cpp

../obj/nzgui/moc_NZChatWidget.o: gen/moc_NZChatWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZChatWidget.o gen/moc_NZChatWidget.cpp

../obj/nzgui/moc_NZConnectionWidget.o: gen/moc_NZConnectionWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZConnectionWidget.o gen/moc_NZConnectionWidget.cpp

../obj/nzgui/moc_NZContact.o: gen/moc_NZContact.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZContact.o gen/moc_NZContact.cpp

../obj/nzgui/moc_NZContactListWidget.o: gen/moc_NZContactListWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZContactListWidget.o gen/moc_NZContactListWidget.cpp

../obj/nzgui/moc_NZContactModel.o: gen/moc_NZContactModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZContactModel.o gen/moc_NZContactModel.cpp

../obj/nzgui/moc_NZControllerProxy.o: gen/moc_NZControllerProxy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZControllerProxy.o gen/moc_NZControllerProxy.cpp

../obj/nzgui/moc_NZConversation.o: gen/moc_NZConversation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZConversation.o gen/moc_NZConversation.cpp

../obj/nzgui/moc_NZGuiController.o: gen/moc_NZGuiController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZGuiController.o gen/moc_NZGuiController.cpp

../obj/nzgui/moc_NZMainWindow.o: gen/moc_NZMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZMainWindow.o gen/moc_NZMainWindow.cpp

../obj/nzgui/moc_NZSideBarWidget.o: gen/moc_NZSideBarWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZSideBarWidget.o gen/moc_NZSideBarWidget.cpp

../obj/nzgui/moc_NZStatusWidget.o: gen/moc_NZStatusWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/moc_NZStatusWidget.o gen/moc_NZStatusWidget.cpp

../obj/nzgui/qrc_nzgui.o: gen/qrc_nzgui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/nzgui/qrc_nzgui.o gen/qrc_nzgui.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

